### ISSUE TITLE
no such signature file exceptions

### ISSUE THREAD

**Issue by pdpol** [goncalopp/keystroke_dynamics#1]
Hi,

I'm trying to test out your algorithm but I don't have either of the signature files loaded for analysis. Are the goncalo and yuna signature files something you might be able to provide? Or would there be some way for me to to generate my own such files? Thanks!
- Paul

**Comment by gitanat** [comment]
Hi,

This project was rather poorly written, since it was a weekend project and I didn't get back to it in 5 years. I've rewritten most of the code today, and hopefully it's much more readable now :) With that being said, the similarity metric is still very crude at the moment, you may want to come up with something smarter

Regarding the signature files you mentioned, those are the files that contain the data that uniquely identifies a typist (so I won't publish them). I've written a interactive `example.py`, which offers a wizard to automatically create fingerprint files and match them.

I hope that helps!
Cheers

**Comment by pdpol** [comment]
Awesome, thanks! Just tested out the new script and it works great. I'm in a biometrics class presenting on keyboard dynamics and will be showing off your script, with appropriate credits of course :)

**Comment by gitanat** [comment]
That's great :) I have some new data, so I'll see if I can make the thing more accurate (and readable) in the next couple of days. Thanks for renewing my interest on this project, and good luck with the presentation!
